### ISSUE TITLE
Console log warnings

### ISSUE THREAD

**Issue by tonyducvo000** [tonyducvo000/react_map_proj#5]
Investigate and resolve warnings in the console log. Currently, the logs are very cluttered. 😬

Below are the issues found in console.log.

**Comment by tonyducvo000** [comment]
1.

Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Wrapper

**Comment by tonyducvo000** [comment]
2.

 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Wrapper component.

**Comment by tonyducvo000** [comment]
3.
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `InfoWindow`, expected a single ReactElement.
    at InfoWindow (http://localhost:3000/static/js/vendors~main.chunk.js:1701:7)
    at MapContainer (http://localhost:3000/static/js/main.chunk.js:335:5)
    at div
    at Wrapper (http://localhost:3000/static/js/vendors~main.chunk.js:969:11)
    at App

**Comment by tonyducvo000** [comment]
4.
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `MapContainer`. See https://reactjs.org/link/warning-keys for more information.
    at Marker (http://localhost:3000/static/js/vendors~main.chunk.js:1956:7)
    at MapContainer (http://localhost:3000/static/js/main.chunk.js:335:5)
    at div
    at Wrapper (http://localhost:3000/static/js/vendors~main.chunk.js:969:11)
    at App

**Comment by tonyducvo000** [comment]
5.
 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `InfoWindow`, expected a single ReactElement.
    at InfoWindow (http://localhost:3000/static/js/vendors~main.chunk.js:1701:7)
    at Map (http://localhost:3000/static/js/vendors~main.chunk.js:2922:7)
    at div
    at MapContainer (http://localhost:3000/static/js/main.chunk.js:335:5)
    at div
    at Wrapper (http://localhost:3000/static/js/vendors~main.chunk.js:969:11)
    at App

**Comment by tonyducvo000** [comment]
7.

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

**Comment by tonyducvo000** [comment]
8.

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Wrapper

**Comment by Srinu126** [comment]
I believe I can resolve this . can you assign this issue to me

**Comment by Srinu126** [comment]
Failed to compile
./src/components/MapContainer.jsx
Module not found: Can't resolve '../key/my_key' in 'C:\Users\user_name\react_map_proj\src\components'
I am getting this error while setting it up locally.How to resolve this?

**Comment by tonyducvo000** [comment]
@Srinu126 
The API key in my_key was ignored by .gitignore, since having it publicly available is bad practice.

You will need to generate your own Google Map API key.  Here's a link to get you started.  https://developers.google.com/maps/documentation/javascript/get-api-key.  Once you get an API KEY, put the key in /src/key/my_key.jsx.

Example my_key.jsx file:
const GOOGLE_MAP_API_KEY = "API KEY HERE"
export default GOOGLE_MAP_API_KEY 

This will export the key and allow you to use it in MapContainer.jsx

**Comment by tonyducvo000** [comment]
-Warning 1 is not resolved - will not fix.  This is not due to any of the components, but due to GoogleApiWrapper().

-Warning 2 is not resolved - will not fix.  This warning is related to GoogleApiWrapper().

-Warning 3 is resolved.  Needed to wrap \<RobotDataDisplay\> and \<ProductInfoDisplay\> in \<div\>, in order to pass as a single element to \<InfoWindow\>.

-Warning 4 is resolved.  Needed to add in key attribute for \<Marker\>.  This attribute is needed every time .map() is used. 

-Warning 5 is resolved.  This is a duplicate of warning # 3.
